Add Precompiles Page
ethereum-optimism/specs pull request #153
Opened 2024-04-24 23:19 UTC by danyalprout

**Description**

As part of Fjord we've added a precompile for [RIP-7212](https://github.com/ethereum/RIPs/blob/master/RIPS/rip-7212.md). This is documented in the [Fjord overview](https://github.com/ethereum-optimism/specs/blob/main/specs/fjord/overview.md), but it maybe useful to have a centralized precompiles page, similar to how we have a predeploys and preinstalls page.

2024-04-25 16:00 UTC, sebastianst requested changes
Thanks!

2024-04-25 16:00 UTC, sebastianst commented on specs/glossary.md
> +[predeploy]: glossary.md#precompiled-contract-precompile
```suggestion
[precompile]: glossary.md#precompiled-contract-precompile
```

2024-04-25 16:00 UTC, sebastianst commented on specs/protocol/precompiles.md
> +## P256VERIFY
I think it's also worth backlinking to this section from the Fjord overview page where RIP-7212 is listed as a feature.

2024-04-25 16:00 UTC, sebastianst commented on specs/glossary.md
> +  - [Precompiled Contract ("Precompile")](#precompiled-contract-precompile)
I would actually list it before Predeploys. Then we go from most to less native.

2024-04-25 16:00 UTC, sebastianst commented on specs/SUMMARY.md
> +  - [Precompiles](./protocol/precompiles.md)
Same, I would list it before Predeploys. Then we go from most to less native.

2024-04-25 17:28 UTC, danyalprout commented on specs/protocol/precompiles.md
> +## P256VERIFY
I updated the Fjord overview page to link here, which has a link to the RIP. If you think it's worth keeping both the precompile and RIP link on the overview page -- let me know.

2024-04-26 11:10 UTC, sebastianst approved these changes

2024-05-15 16:59 UTC, tynes approved these changes

2024-05-15 16:59 UTC, merged