std-config: initial proposal
ethereum-optimism/specs pull request #93
Opened 2024-03-15 21:13 UTC by mds1

## Overview

This is a draft proposal defining the Standard Configuration for OP Stack chains. A standard chain does not need to be interoperable, but must support fault proofs and handover their keys. (Read more in [What is the Superchain](https://docs.google.com/presentation/d/1IBHw_KR96DgRaGCvxMSlqMMA3FshbYap9jTQFBO6SXo/edit#slide=id.g269a303f9b1_0_907)).

This PR is largely a port of the [Standard Config Strawman](https://www.notion.so/Standard-Config-Strawman-505874b0b0d24e5f90d47289d8f98485?pvs=4) by @ben-chain. 

## How to Review

There are many outstanding TODOs which we must discuss and finalize before taking this PR out of draft. The asks for reviewers are:
1. Review all requirements.
    1. For requirements that specify a value, leave a comment if you disagree with the value or justification.
    2. For requirements with a TODO, leave a comment proposing a value (there are many of these!)
2. If any requirements are missing, erroneous, unclear, etc. please leave a comment

We should aim avoid breaking changes to these requirements—we don't want a chain that previously met the Standard Configuration requirements to suddenly no longer be considered a standard chain, potentially with no path back in. Therefore we should start by keeping requirements strict, and we can loosen them over time as we learn more.

## Path Forward

1. Once merged, we will need to ensure future spec updates also update the standard config, when applicable. 
2. The actual format of this PR (i.e. markdown tables) may not be the final format. We want a human-readable source of truth (what this PR provides) but we also want a machine-readable version for validation scripts in the [superchain-registry](https://github.com/ethereum-optimism/superchain-registry). So the final format ("source of truth markdown, registry parses that", or "source of truth TOML in the registry, specs parse that", or something else) is still TBD

2024-03-18 14:58 UTC, zchn requested changes

2024-03-18 14:58 UTC, zchn commented on specs/standard-configuration/overview.md
> +TODO add copy about standard chains / why a chain may want to be a standard chain
Is this necessary for this PR? Can we leave this to a later PR?

2024-03-18 14:58 UTC, zchn commented on specs/standard-configuration/protocol-parameters.md
> +| Sequencing Window                     | TODO                                                           | High security.
Asked in #node, https://oplabs-pbc.slack.com/archives/C01HLRH0LKZ/p1710772932465259

2024-03-18 14:58 UTC, zchn commented on specs/standard-configuration/protocol-parameters.md
> +| Output Frequency                      | TODO this won't exist post-FPAC, should we include it?         | TODO
How about `1800 seconds` which is used at least by both OP Mainnet and Mode?

> TODO this won't exist post-FPAC, should we include it?

I think we should focus on what we have *now* in this PR, and have a followup PR at the time when we upgrade OP Mainnet with FP. Too early to make decisions on FP parameters w.r.t. std config.

2024-03-18 14:58 UTC, zchn commented on specs/standard-configuration/protocol-parameters.md
> +| Batch Inbox Address                   | TODO, ideally function of 32 byte chain ID                     | TODO
Why do we need to require this? Can we remove this for now? I don't see a benefit or reason to mandate anything about batch inbox.

2024-03-18 14:58 UTC, zchn commented on specs/standard-configuration/protocol-parameters.md
> +| Fee Vault Contracts                   | Standard revenue share contract deployment [^fee-vault]        | TODO
Can we remove this for now and rely on [this process](https://docs.google.com/document/d/1lvoZOCwQvmLSJwApCsMv2dMEwlLsYdpHr7R0IZszZOo/edit#heading=h.kl5u4vro3tn0) to update the config once we make progress here?

2024-03-18 14:58 UTC, zchn commented on specs/standard-configuration/protocol-parameters.md
> +| Resource Config                       | TODO.                                                          | High security, changes here can lead to security vulnerabilities.
How about just use `20000000,10,8,1000000000,1000000,340282366920938463463374607431768211455` since that's the value for both OP Mainnet and Mode?

2024-03-18 14:58 UTC, zchn commented on specs/standard-configuration/protocol-parameters.md
> +| Target Gas Rate                       | TODO, defined as a function of Resource Config?                | TODO.
What are the values for OP Mainnet and Mode?

2024-03-18 14:58 UTC, zchn commented on specs/standard-configuration/protocol-parameters.md
> +| Gas Limit                             | TODO                                                           | Must have well-tested gaslimit for uptime properties, also dangerously affects EIP1559 param
What are the values for OP Mainnet and Mode?

2024-03-18 14:58 UTC, zchn commented on specs/standard-configuration/protocol-parameters.md
> +TODO check other lists such as
Do we need to address this TODO in this PR? If not, let's remove and track it in an issue instead?

2024-03-18 14:58 UTC, zchn commented on specs/standard-configuration/protocol-parameters.md
> +TODO process for foundation approval?.
Do we need to address this TODO in this PR? If not, let's remove and track it in an issue instead?

2024-03-18 14:58 UTC, zchn commented on specs/standard-configuration/protocol-parameters.md
> +The standard revenue share contract is TODO, and the steps to deploy and configure it are TODO.
Let's remove since we don't have it. And add it by following [this process](https://docs.google.com/document/d/1lvoZOCwQvmLSJwApCsMv2dMEwlLsYdpHr7R0IZszZOo/edit#heading=h.kl5u4vro3tn0) in the future?

2024-03-18 14:58 UTC, zchn commented on specs/standard-configuration/admin-roles.md
> +The Chain Governor is TODO.
How about "The Chain Governor is defined in the [Law of Chains](https://github.com/ethereum-optimism/OPerating-manual/blob/main/Law%20of%20Chains.md)." ?

2024-03-18 14:58 UTC, zchn commented on specs/standard-configuration/admin-roles.md
> +| L2 Proxy Admin       | TODO                                                        | Governance-controlled, high security.
How about `Chain Governor for now, and will be eliminated or transitioned to a similar control structure as L1 ProxyAdmin in the future`?

2024-03-18 14:58 UTC, zchn commented on specs/standard-configuration/admin-roles.md
> +| Mint Manager Owner   | TODO not relevant on other chains since no native OP token? | TODO
How about just remove this from the table?

2024-03-18 14:58 UTC, zchn commented on specs/standard-configuration/servicer-roles.md
> +| Batch Submitter Account                    | TODO can we standardize as a deterministic function of chain ID? |                     |
Can we remove this from the table for this PR and worry about it in a future PR?

2024-03-18 14:58 UTC, zchn commented on specs/standard-configuration/servicer-roles.md
> +| Challenger Account                         | TODO                                                             |                     |
How about also `Optimism Foundation Safe`?

2024-03-18 16:13 UTC, zchn commented on specs/standard-configuration/protocol-parameters.md
> +| Sequencing Window                     | TODO                                                           | High security.
How about requiring it to be `12h` which is what we currently require?
From Subject Matter Expert: 

> 
It's currently 12h and it's hardcoded in the op-node's [superchain configuration loader](https://github.com/ethereum-optimism/optimism/blob/56f3d1b60b3ba3d7019c159180abf60e11479600/op-node/rollup/superchain.go#L96). The comment above states that it might get configurable in the future, but right now it's hardcoded because all op stack chains with a superchain config use this value. Chains who don't want to use it have to overwrite it with a custom rollup config. Note that its unit is L1-blocks (3600 * 12 / 60 / 60 = 12)

2024-03-18 16:22 UTC, ben-chain commented on specs/standard-configuration/admin-roles.md
> +The Chain Governor is TODO.
agree.  Better yet:

> The Chain Governor is defined in the Law of Chains, and address verification is implemented as a manual/social-layer check during PR review.

In other words: "validation" of the Chain Governor address should at this point be performed by social verification by us -- e.g. via out of band communication, or confirmation that the PR submitter is a known contributor to the Chain Governor's github org, etc.

2024-03-18 16:28 UTC, mds1 commented on specs/standard-configuration/protocol-parameters.md
> +| Batch Inbox Address                   | TODO, ideally function of 32 byte chain ID                     | TODO
We are now tracking this in https://github.com/ethereum-optimism/specs/issues/94. In general we should start with strict requirements and loosen them over time, which would be an argument in favor of not removing this

One benefit @tynes has discussed around standardizing this is to enable counterfactual chains where properties like its batch inbox are known beforehand, so messages can be sent in advance.

2024-03-18 16:32 UTC, mds1 commented on specs/standard-configuration/servicer-roles.md
> +| Batch Submitter Account                    | TODO can we standardize as a deterministic function of chain ID? |                     |
Ah I meant to put no requirement here, fixed in a2c3f09

2024-03-18 16:56 UTC, ben-chain commented on specs/standard-configuration/admin-roles.md
> +| Mint Manager Owner   | TODO not relevant on other chains since no native OP token? | TODO
Agree, although there's something to do with predeploys that may matter here. (i.e.-- we should make sure to restrict ability to set `0x42000000...42` address to ensure forwards-compatibility)

2024-03-18 16:56 UTC, ben-chain commented on specs/standard-configuration/overview.md
> +TODO add copy about standard chains / why a chain may want to be a standard chain
agree

2024-03-18 16:56 UTC, ben-chain commented on specs/standard-configuration/protocol-parameters.md
> +| Sequencing Window                     | TODO                                                           | High security.
if it's hardcoded, then yes def just stay with that restriction

2024-03-18 16:56 UTC, ben-chain commented on specs/standard-configuration/protocol-parameters.md
> +| Batch Inbox Address                   | TODO, ideally function of 32 byte chain ID                     | TODO
Slipper also requested standardization [here](https://www.notion.so/Standard-Config-Strawman-505874b0b0d24e5f90d47289d8f98485?d=b7fbd86f34bf41fea94ea48121d7c499&pvs=4#c3100479c56d47aeaf563c4001cada7d).  I agree with standardizing this, seems strictly beneficial, but if there are some chains out there which don't currently conform, we should track the work to get them back on standard.  And if that's too much work, drop restriction for now

2024-03-18 16:56 UTC, ben-chain commented on specs/standard-configuration/protocol-parameters.md
> +| Fee Vault Contracts                   | Standard revenue share contract deployment [^fee-vault]        | TODO
agree

2024-03-27 17:56 UTC, zchn commented
removing myself and assigning to @blmalone instead for the review of this PR since @mds1 and @blmalone are working on this together.

2024-04-17 21:57 UTC, blmalone commented
@mds1 closing this pr in favor of: https://github.com/ethereum-optimism/specs/pull/134

2024-04-17 21:57 UTC, closed without merging